### ISSUE TITLE
Usage of DarIA Images

### ISSUE THREAD

**Issue by EStorvik** [pmgbergen/DarIA#36]
At the moment, several of the newer routines are performed without the use of DarIA images. I suppose that this is because the features that the DarIA images provide in some sense is useless for those routines. However, if we want to keep the Image-class I suggest that we make all routines run on DarIA images instead of image-matrices. That way we can limit the direct user interface to external libraries, perhaps completely, as well as automatically transform between BRG and RBG where it is natural.

**Comment by jwboth** [comment]
There is indeed very few features that `daria.Image` provides which is of greater importance for any postprocessing. Mainly the coordinate system is of greater use so far. Other than that the class actually only provides very litte functionality required for the analysis itself. It is more output routines.

Note however, that the for instance `daria.Image` is very useful to have for `daria.Patches`. Here the knowledge of the coordinates of the corners and centers of the patches are directly obtained from objects as the coordinate system.

At this stage, I would not be to concerned with this issue. In my opinion, the development of daria is still in a fast-growing phase. We can still make an extra effort when we know what we want and what for. I can imagine that patches will become more relevant in the near future. And then also `daria.Image`
