### ISSUE TITLE
Ordering of entries when talking about physical coordinates vs pixels of an image

### ISSUE THREAD

**Issue by jwboth** [pmgbergen/DarIA#38]
When addressing locations, there is two conventions. One is the physical/Cartesian one, when we think of x and y axis and address coordinates by providing pairs like (x,y). The other is the standard for images which seems to flip x and y and starts at the top for y. A more useful way of thinking about this (instead of the flip etc.) is to think about a (row,col) address. When interpreting an image as a matrix and we want to address some pixel, addressing (row,col) is very much natural. 

My suggestion is that we try stick to both conventions, and make use of the most suitable convention for the particular situation. So when we talk about coordinates we choose a (x,y) order, and when addressing pixels, we use the (row, col) order.

There will be need for a switch between the conventions. There is routines in utils which do the job. Maybe we should also try to use interface functions like these (maybe they need some revision, I am not sure) to make the switch very apparent in the code. 

In start of the development of Daria, (unfortunately) I have made a lot of comments throughout the code, which address which order to use. At that time, I was not disturbed by the (row,col) convention. But now I completely changed my mind. Especially since many (unfortunately not all of the) routines in cv2 and skimage also use the (row, col) format.

I would like to suggest another overhaul, which addresses this issue and cleans up all comments. Maybe even (if this happens somewhere), correct wrong use in the code.

**Comment by jwboth** [comment]
And we should decide on a fixed way of calling the two conventions. I like Cartesian ordering better than "physical" for (x,y). And I think I would vote for pixel ordering for [row,col] - or do you maybe have another suggestion @EStorvik ?

**Comment by EStorvik** [comment]
I like the cartesian word when we just talk about ordering. But when scaling is applied so that it actually is the physical coordinates we refer to I think that it is at least debatable. Anyways, I think that cartesian is fine, and that making a choice of words instead of mixing them is more important than choosing the most appropriate word.

**Comment by jwboth** [comment]
You are right. There will be situation, when the coordinates actually will not make much sense. I am e.g. thinking about the teh FluidFlower before and after the correction. Of course, we do not want to transform the wrong coordinate system set up in the initialization of a `daria.Image`, but only the same one but applied to the corrected image. I think we will have to live with that.

OK, I will then go for cartesian and pixel ordering. If it is OK, I will mix these changes with those proposed in #37. The I will only have to read all files once.

**Comment by EStorvik** [comment]
Absolutely, go for it!

**Comment by jwboth** [comment]
I chose to go for the use of 'Cartesian indexing' and 'matrix indexing' instead of 'Cartesian ordering' and 'pixel ordering'. This choice is inspired by the documentation of np.meshgrid.
