### ISSUE TITLE
Use of Path and pathlib

### ISSUE THREAD

**Issue by jwboth** [pmgbergen/DarIA#45]
A consistent use of str and Path for addressing paths of files is needed. 

It will be best if we can remove the use of Path from the user, I believe.

**Comment by EStorvik** [comment]
Good idea! I'll try to fix it and make a PR this evening.

**Comment by jwboth** [comment]
Go ahead if you wish. Currently, this was meant as a reminder and TODO. I think it would be great to have this in place soon, but I also believe that many issues of this type will appear once we start having real use cases for daria as the benchmark analysis, e.g.
