### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by EStorvik** [pmgbergen/DarIA#46]
We should probably find a good way to include some pytest tests.

**Comment by jwboth** [comment]
I agree, that daria is lacking tests. Right now, this is less of a priority for me, but I would like to come back to tests in about 1.5-2 weeks!

**Comment by EStorvik** [comment]
I was actually just going to write an issue about this. And I agree. Some of the examples should be modified according to the new curvature corrections. I suggest just using the config.json that is in the examples/images folder (or make a similar one) to initialize the curvature correction and just make some comment with a reference to the notebook or example that explains how to create the config. Great if you take care of it!

**Comment by EStorvik** [comment]
This sounds like a good idea. I will try to do this tomorrow morning! Activating pytest in actions is easy, but it struggled with scipy when I imported daria for some reason. I'll try to figure out why.

**Comment by jwboth** [comment]
Shall we close this issue @EStorvik ? To me it seems the groundwork is done for including examples as tests, which in the end fixes exactly the issue we started with, or not? Of course one can always add more examples. But this is another issue.

**Comment by EStorvik** [comment]
Agreed! Let's just close it.
