### ISSUE TITLE
Curvature correction vs geometry correction

### ISSUE THREAD

**Issue by EStorvik** [pmgbergen/DarIA#62]
While thinking about how to present the code to non-FluidFlower users it occured to me that renaming curvature correction to something like geometry correction might be a good choice. Right now, curvature is the main focus, but especially the crop part might be important also for other applications where the images for example are taken from a slightly "non-centered" angle. What do you think @jwboth?

**Comment by jwboth** [comment]
I agree. I even had similar thoughts, that correction is maybe also a bit strict. In first place, all of the objects are "transformations". Either addressing the geometry/the shape or the colorspace. But on the other hand, all these objects are at the moment used to really "correct" for some effects. So keeping the name here my be likewise OK.

Anyhow, I am OK with renaming curvature to geometry. 

And indeed, I can foresee examples in which merely the crop part is of interest.

**Comment by jwboth** [comment]
I think at this stage we should not change the name anymore as too many people (it is not that many, but still) have scripts set up. We can think about such changes after the benchmark evaluation. To clean the list of issues, I would therefore suggest postponing this issue. Even closing it could be OK for me, as we won't touch it over the next weeks.

**Comment by EStorvik** [comment]
Agreed!
